on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build-ci-pizza-planet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - uses: syphar/restore-virtualenv@v1
          id: cache-virtualenv
          with:
            requirement_files: requirements.txt 

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # the package installation will only be executed when the
      # requirements-files have changed.
    - run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Test
      run: python manage.py test
